import streamlit as st
from langsmith import Client, traceable
from langsmith.run_helpers import get_current_run_tree
from src.assistant_vector import create_assistant

client = Client()

def send_feedback(run_id, score, comment=None):
    """Submits user feedback directly via LangSmith SDK."""
    client.create_feedback(
        run_id=run_id,
        key="user_feedback",
        score=score,
        comment=comment,
    )
    st.toast("Feedback submitted! Thank you.")

# 1. Wrap your custom execution logic with @traceable
@traceable(name="Coffee Bean RAG Execution")
def run_rag_pipeline(prompt_text):
    # Call your raw RAG code/assistant
    rag_result = assistant.rag(prompt_text)
    
    # Extract the current run_id generated by LangSmith
    current_run = get_current_run_tree()
    run_id = str(current_run.id) if current_run else None
    
    return rag_result, run_id

# 2. Page Configuration
st.set_page_config(
    page_title="BeanRAG",
    page_icon="☕",
    layout="centered"
)

# 3. Cache Assistant Initialization
@st.cache_resource
def load_assistant():
    return create_assistant()

assistant = load_assistant()

# 4. Initialize Session State
if "messages" not in st.session_state:
    st.session_state.messages = []

# Sidebar Controls
with st.sidebar:
    st.title("☕ BeanRAG Settings")
    st.markdown("Your expert RAG assistant for coffee beans")
    if st.button("Clear Conversation", type="secondary"):
        st.session_state.messages = []
        st.rerun()

# Title Header
st.title("☕ Coffee Bean Knowledge Base")

# 5. Render Conversation History & Feedback Buttons
for idx, message in enumerate(st.session_state.messages):
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        
        # Render retrieved sources
        if "sources" in message and message["sources"]:
            with st.expander("View Retrieved Context"):
                st.write(message["sources"])
                
        # Render feedback UI for assistant messages with a trace ID
        if message["role"] == "assistant" and message.get("run_id"):
            run_id = message["run_id"]
            col1, col2, _ = st.columns([1, 1, 10])
            with col1:
                if st.button("👍", key=f"up_{idx}"):
                    send_feedback(run_id=run_id, score=1)
            with col2:
                if st.button("👎", key=f"down_{idx}"):
                    send_feedback(run_id=run_id, score=0)

# 6. Process User Input
if prompt := st.chat_input("Ask anything about coffee beans..."):
    
    # Display & Save User Message
    with st.chat_message("user"):
        st.markdown(prompt)
    st.session_state.messages.append({"role": "user", "content": prompt})

    # Generate Assistant Response
    with st.chat_message("assistant"):
        with st.spinner("Searching knowledge base..."):
            try:
                # Call traceable function (Logs to LangSmith automatically)
                rag_result, run_id = run_rag_pipeline(prompt)

                # Extract outputs
                response_text = rag_result.output_text
                retrieved_sources = getattr(rag_result, "sources", None) or getattr(rag_result, "context", None)

                # Render Response
                st.markdown(response_text)

                # Render Sources
                if retrieved_sources:
                    with st.expander("View Retrieved Context"):
                        st.write(retrieved_sources)

                # Save to State with run_id
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": response_text,
                    "sources": retrieved_sources,
                    "run_id": run_id,
                })
                
                st.rerun()

            except Exception as e:
                st.error(f"Failed to generate response: {str(e)}")