[project]
name = "coffe-bean-reviews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langsmith>=0.10.9",
    "minsearch>=0.2.0",
    "numpy>=2.4.4",
    "onnxruntime>=1.27.0",
    "openai>=2.45.0",
    "pandas>=3.0.3",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.2",
    "streamlit>=1.59.2",
    "tokenizers>=0.22.2",
    "tqdm>=4.66.5",
]
[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"

[dependency-groups]
dev = [
    "huggingface-hub>=1.24.0",
    "jupyter>=1.1.1",
]
